### ISSUE TITLE
能导出链接，但是无法下载

### ISSUE THREAD

**Issue by toseeu** [ewigl/gofile-userscript#2]
不管是使用 IDM 还是 Aria2 都无法正常下载 Gofile 的文件。只会获得一个 9 KB 的文件。不知道是需要修改 UA，还是需要传递浏览器 cookie。 作者大大是怎么利用 IDM 下载 Gofile 的文件的？ 感谢

**Comment by ewigl** [comment]
> 不管是使用 IDM 还是 Aria2 都无法正常下载 Gofile 的文件。只会获得一个 9 KB 的文件。不知道是需要修改 UA，还是需要传递浏览器 cookie。 作者大大是怎么利用 IDM 下载 Gofile 的文件的？ 感谢

我测试了下面两个UA，IDM 的默认 UA 和浏览器 UA，下载都正常。

IDM: `Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0`

Chrome: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`

--- 

没有设置 Cookie 等额外的操作，操作流程就是按照示例视频来的。

aria2 我没有使用，暂时无法测试。

---

也许是网络问题？

可以考虑提供一下你说的9kb的文件，或许能找到原因。

**Comment by toseeu** [comment]
> > 不管是使用 IDM 还是 Aria2 都无法正常下载 Gofile 的文件。只会获得一个 9 KB 的文件。不知道是需要修改 UA，还是需要传递浏览器 cookie。 作者大大是怎么利用 IDM 下载 Gofile 的文件的？ 感谢
> 
> 我测试了下面两个UA，IDM 的默认 UA 和浏览器 UA，下载都正常。
> 
> IDM: `Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0`
> 
> Chrome: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`
> 
> 没有设置 Cookie 等额外的操作，操作流程就是按照示例视频来的。
> 
> aria2 我没有使用，暂时无法测试。
> 
> 也许是网络问题？
> 
> 可以考虑提供一下你说的9kb的文件，或许能找到原因。

这个是示例链接 https://gofile.io/d/SdzOUq
其中，IDM 导入之后，无法获取文件类型和大小。（不知道是浏览器少传递了什么信息）
![image](https://github.com/user-attachments/assets/b9a4e7cd-199a-41ac-8aad-de403c3fabd7)
如果用 Aria2 下载，会迅速结束并获得一个 9 KB 的文件
[下载文件.zip](https://github.com/user-attachments/files/17658784/default.zip)
因 Github 上传附件限制。所以打包成 zip 格式的压缩包。
其中，d9b24702-a43c-4380-872d-b96cb94a8cde 是 Aria2 下载获取到的文件。
    SdzOUq - 1730968939764.txt 为脚本获取到的文件。链接是没有问题的，浏览器下载文件获取到的就是这个链接。

所以我只能想到，下载百度网盘的脚本，是带 cookie 和 UA 传递的，Gofile 是否也存在这个情况。

**Comment by ewigl** [comment]
IDM 无法获取信息是浏览器集成问题，需要在IDM设置里启用“使用高级浏览器集成”。

---

Aria2 我刚测试了一下，确实是因为 Cookie 的问题，需要自定义请求头 Cookie

![image](https://github.com/user-attachments/assets/1e11e691-cc30-46b1-8a04-10b4958a255e)

之前忽略了这一点，等有时间我再适配一下 Aria2 吧...

**Comment by ewigl** [comment]
我也找到了不启用 IDM 高级浏览器集成就能使用 IDM 下载的方法，之后再更新吧...

**Comment by toseeu** [comment]
> IDM 无法获取信息是浏览器集成问题，需要在IDM设置里启用“使用高级浏览器集成”。
> 
> Aria2 我刚测试了一下，确实是因为 Cookie 的问题，需要自定义请求头 Cookie
> 
> ![image](https://private-user-images.githubusercontent.com/43067606/383901990-1e11e691-cc30-46b1-8a04-10b4958a255e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMjYzNjUsIm5iZiI6MTczMTAyNjA2NSwicGF0aCI6Ii80MzA2NzYwNi8zODM5MDE5OTAtMWUxMWU2OTEtY2MzMC00NmIxLThhMDQtMTBiNDk1OGEyNTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAwMzQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTQzZjU4MGZlYWI1MzQ1MWEwNjZiYWM4NjA5NmQyN2Y2MmVlNWU2MWYzYzc2ZWI1NDFkZDFmNjE0ZGMxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7qn0fA4zBMM8y8H0USxlBYAOUovjJS302uaCUVXl1kQ)
> 
> 之前忽略了这一点，等有时间我再适配一下 Aria2 吧...

Aria2 建议参考 [网盘直链下载助手](https://github.com/syhyz1990/baiduyun)。 脚本里边设置 Aria2 的信息。然后一键发送。
至于 Web 管理的 AriaNG 其实脚本没必要集成。正常的 Aria2 玩家自己有 WebUI 或者会直接命令行。

***

IDM 是我的问题。我这台电脑没安装 IDM ，直接用 Aria2 下载了。所以是看到你的演示才把导出的链接复制到有 IDM 的电脑上。如果日常使用 IDM 作为下载器的 不会存在这个问题。 
再次感谢大佬帮忙排查问题！

**Comment by ewigl** [comment]
添加了 IDM 专用格式 ef2 文件导出功能。

添加了 Aria2 RPC 下载方式。

均携带 Cookie。
